const opportunities = [
  { id:"freight", rank:1, score:93, name:"AI Freight Invoice Recovery", short:"FreightLeak", category:"commerce", label:"Recovery", geography:"Türkiye / EU", model:"Success fee · SaaS", mvp:"4–6 hafta", color:"coral", summary:"Taşıyıcı faturası, rate card ve shipment verisini karşılaştırır; yanlış ücretleri bulur, kanıt dosyası ve itiraz metni üretir.", wedge:"Faturayı muhasebeleştirmek değil, ‘bu parayı gerçekten ödemeli miydik?’ sorusunu çözmek.", customer:"€250K+ freight spend yapan ihracatçı, importer, 3PL veya yüksek hacimli e-ticaret şirketi.", revenue:"Geri alınan tutarın %15–25’i · €299–999/ay + recovery", risk:"Karmaşık tarife ve surcharge kuralları yanlış pozitif üretirse güven kaybolur.", next:"Son 100 faturayı ücretsiz tara; bulunan leakage’i üç gerçek carrier dispute’unda doğrula.", source:"nShift Audit · Recoup Labs · Freight AuditBench" },
  { id:"kanzlei", rank:2, score:92, name:"AI-Managed Kanzlei Backoffice", short:"KanzleiFlow", category:"b2b", label:"Vertical AI", geography:"Almanya / DACH", model:"B2B SaaS", mvp:"6–8 hafta", color:"lime", summary:"Steuerkanzlei’lerin belge, exception, deadline ve müşteri iletişimi iş akışını yönetir; yeni Buchhalter almadan kapasite açar.", wedge:"Bir AI aracı daha değil; ‘100 ek Mandant kapasitesi’ vaadi.", customer:"3–30 çalışanlı Steuerkanzlei; DATEV workflow’u ve tekrar eden exception yükü olan ekipler.", revenue:"€499–2.500/ay · setup ve human-review katmanı", risk:"DATEV entegrasyonu, DSGVO ve yanlış muhasebe çıktısının sorumluluğu.", next:"Tek bir Kanzlei’de 100 gerçek belgeyi concierge modelle işle; saat ve exception tasarrufunu ölç.", source:"Neno · Rational · Alman personel açığı sinyali" },
  { id:"fieldwork", rank:3, score:91, name:"Fieldwork API", short:"Fieldwork API", category:"b2b", label:"Physical API", geography:"EU / Türkiye", model:"Task fee · API", mvp:"6–10 hafta", color:"blue", summary:"AI ajanları için fiziksel dünyada doğrulanabilir görev çalıştırır: fotoğraf, GPS, mağaza kontrolü, teslimat ve inspection.", wedge:"Broad errands marketplace değil; B2B doğrulama işlerinin API katmanı.", customer:"Retail, emlak, sigorta, lojistik, EV charging ve saha araştırması ekipleri.", revenue:"Görev başına %20–30 take-rate · €299–1.999/ay API", risk:"Worker kalitesi, sahte kanıt ve şehir bazlı arz ekonomisi.", next:"Berlin, Hannover ve İstanbul’da üç tekrarlanabilir görev tipiyle 25 ücretli iş tamamla.", source:"RentAHuman · Mundane · TaskPick / mystery-shopping ağları" },
  { id:"marketplace-recovery", rank:4, score:92, name:"Marketplace Revenue Recovery OS", short:"KesintiAvcısı", category:"commerce", label:"Recovery", geography:"Türkiye-first", model:"Success fee · SaaS", mvp:"3–5 hafta", color:"coral", summary:"Trendyol veya Hepsiburada settlement verisindeki fazla kesinti, yanlış kargo baremi ve reimbursement fırsatlarını bulur.", wedge:"Net kâr göstermek değil; geçmişte kesilmiş ve geri alınabilir parayı kanıtlamak.", customer:"500+ sipariş/ay yapan marketplace mağazası veya çoklu mağaza yöneten ajans.", revenue:"Recovery %15–25 · Pro ₺2.000–5.000/ay · Agency ₺10.000+", risk:"Anomaly ile gerçekten claimable kesintiyi birbirine karıştırmak.", next:"20 mağazanın son altı aylık settlement dosyasını tara; üç farklı anomaly sınıfını manuel doğrula.", source:"ReclaimHQ · SellerAIHQ · Türkiye marketplace satıcı sinyalleri" },
  { id:"ad-gatekeeper", rank:5, score:90, name:"Regulated Ad Compliance Gatekeeper", short:"Ad Gatekeeper", category:"trust", label:"Compliance", geography:"Türkiye-first", model:"B2B SaaS", mvp:"3–4 hafta", color:"purple", summary:"Sağlık turizmi ve regüle sektör reklamlarını yayınlanmadan önce mevzuat, platform kuralı ve marka politikasına göre kontrol eder.", wedge:"‘Compliant’ demek yerine source-backed LOW / REVIEW / HIGH RISK kararı.", customer:"Sağlık turizmi ajansları ve 5–50 klinik yöneten performance ekipleri.", revenue:"€99/ay Clinic · €299–799/ay Agency · white-label", risk:"False negative: hukuka aykırı bir reklamı onaylamak.", next:"100 gerçek reklam örneğini kural + kaynak + insan onayı ile etiketle.", source:"Veriad · IntelligenceBank · Reklam Kurulu / Sağlık tanıtım düzeni" },
  { id:"trust-it", rank:6, score:94, name:"Should I Trust It?", short:"ShouldITrustIt", category:"trust", label:"Trust data", geography:"Global · DE focus", model:"Sponsor · Affiliate · API", mvp:"2–4 hafta", color:"lime", summary:"Yazılım, servis ve şirketler için güven skorunu güvenlik, privacy, ownership ve public record sinyallerine ayırır.", wedge:"SAFE / UNSAFE etiketi değil; kaynağı görünen, açıklanabilir trust profile.", customer:"Yazılım satın alan ekipler, geliştiriciler, güvenlik meraklıları ve sponsorlar.", revenue:"10 sabit sponsor · affiliate · verified profile · API", risk:"Skorların güncelliği ve hukuki/itibari sorumluluk.", next:"50 yüksek niyetli ürün için kaynaklı profil yayınla; üç sponsor kategorisiyle CTR test et.", source:"CanIVibecodeIt gelir modeli · privacy/security utility sinyalleri" },
  { id:"host-it", rank:7, score:92, name:"Can I Host It Myself?", short:"Self-host Radar", category:"media", label:"Programmatic SEO", geography:"Global · EU", model:"Affiliate · Sponsor", mvp:"2–3 hafta", color:"blue", summary:"Popüler SaaS’ların self-host edilebilirlik, sunucu maliyeti, zorluk ve açık kaynak alternatifini karşılaştırır.", wedge:"Kullanıcıya yalnız alternatif değil, ‘aylık ne kadar tasarruf ve bakım?’ cevabı verir.", customer:"Indie hacker, developer, privacy odaklı SMB ve hosting sponsorları.", revenue:"VPS affiliate · sponsor · deployment template", risk:"AlternativeTo benzeri içerik rekabeti ve yanlış maliyet varsayımı.", next:"50 ürün için gerçek Docker/hosting reçetesi oluştur; 10 long-tail sorguda SEO testine başla.", source:"Self-hosting ve European privacy demand sinyalleri" },
  { id:"gdpr", rank:8, score:90, name:"GDPR Risk Assessment", short:"Is It GDPR Compliant?", category:"trust", label:"Compliance", geography:"DACH / EU", model:"B2B SaaS · Lead-gen", mvp:"4–6 hafta", color:"purple", summary:"SaaS ürününü data hosting, DPA, SCC, subprocessors ve transfer riskleriyle birlikte değerlendirir.", wedge:"Kesin ‘uyumlu’ iddiası değil; tarihli ve kaynaklı risk assessment.", customer:"DPO, ajans, procurement ve Avrupa’ya satış yapan SaaS ekipleri.", revenue:"Lead-gen · €99–799/ay risk workspace · advisory", risk:"Hukuki tavsiye ile teknik risk analizinin sınırını korumak.", next:"30 yaygın SaaS için aynı rubric’i uygula; iki DPO ile terminoloji ve karar akışını gözden geçir.", source:"Anytype · Nesis · EU privacy-first workspace trendi" },
  { id:"recommerce", rank:9, score:89, name:"Recommerce OS for Turkish Brands", short:"Loopback", category:"commerce", label:"White-label", geography:"Türkiye-first", model:"SaaS · GMV share", mvp:"6–10 hafta", color:"coral", summary:"Fashion, sneaker ve outdoor markalarına trade-in, AI condition grading, store credit ve pre-owned storefront altyapısı verir.", wedge:"İkinci el marketplace olmak değil; markanın kendi retention kanalını açmak.", customer:"Premium fashion, sneaker ve outdoor markaları.", revenue:"₺ / € platform fee · GMV %5–10 · inspection/logistics margin", risk:"Buyback, shipping, inspection ve resale fiyatı arasındaki unit economics.", next:"Bir marka ile 100 ürünlük manuel trade-in pilotu; gerçek resale margin’i hesapla.", source:"eComID × Nilum · reverse.supply · Türkiye C2C büyümesi" },
  { id:"creator", rank:10, score:88, name:"Local Creator × Local Business", short:"Localfluence", category:"media", label:"Marketplace", geography:"DE / Türkiye", model:"Subscription · Campaign fee", mvp:"4–6 hafta", color:"purple", summary:"Restoran ve lokal işletmeleri yakınındaki mikro-creator’larla eşleştirir; brief, ziyaret, içerik ve kupon dönüşümünü takip eder.", wedge:"Ulusal influencer değil; 5 km içindeki güvenilir creator ve ölçülebilir ziyaret.", customer:"Restoran, kuaför, gym, beauty salon ve lokal mağaza.", revenue:"€79–149/ay · kampanya ücreti · performance bonus", risk:"İki taraflı marketplace likiditesi ve içerik kalitesi.", next:"Hildesheim / Hannover’da 20 işletme ve 50 creator ile concierge kampanya yürüt.", source:"TryNearby · Creator Pool Germany" },
  { id:"handwerker", rank:11, score:91, name:"AI Backoffice für Handwerker", short:"HandwerkOS", category:"b2b", label:"Vertical AI", geography:"Almanya / DACH", model:"B2B SaaS", mvp:"4–6 hafta", color:"lime", summary:"Telefon ve WhatsApp talebini alır; fotoğraf ister, işi sınıflandırır, teklif takibi, randevu, fatura ve yorum akışını yürütür.", wedge:"Sanal sekreter değil; iş emrinden tahsilata giden sanal Bürokraft.", customer:"2–30 çalışanlı SHK, elektrik, çatı, PV, Gartenbau işletmesi.", revenue:"€149–499/ay · setup · partner upsell", risk:"SMB satış CAC’i ve mevcut telefon/CRM araçlarıyla entegrasyon.", next:"30 Handwerker görüşmesi, 5 ücretli concierge pilotu, ölçülecek metrik: kazanılan iş.", source:"Async · Boom · DACH AI receptionist rekabeti" },
  { id:"automate", rank:12, score:88, name:"Can I Automate It?", short:"Workflow Radar", category:"media", label:"Utility", geography:"Global · DE/TR", model:"Affiliate · Template", mvp:"3–5 hafta", color:"blue", summary:"Bir operasyonu n8n, Make, Gmail, Sheets ve AI ile otomatikleştirmenin zorluk, süre, maliyet ve hazır workflow’unu verir.", wedge:"‘AI ile olur mu?’ yerine import edilebilir workflow ve tahmini saat tasarrufu.", customer:"SMB, operasyon uzmanı, ajans ve automation tool sponsorları.", revenue:"Template €19+ · affiliate · sponsor · lead-gen", risk:"Arama sorgularının parçalı olması ve generic AI içerik rekabeti.", next:"25 yüksek niyetli iş akışı için gerçek n8n template + ROI hesaplayıcı yayınla.", source:"n8n / Make / Zapier ecosystem" },
  { id:"cheaper", rank:13, score:87, name:"Cheaper European Alternative To", short:"Fairer Alternative", category:"media", label:"Comparison", geography:"EU-first", model:"Affiliate · Lead-gen", mvp:"3–5 hafta", color:"purple", summary:"Pahalı global SaaS’lara Avrupa merkezli, self-hosted veya gerçekten daha ucuz alternatifleri maliyet ve veri konumuyla karşılaştırır.", wedge:"Generic alternative directory değil; ‘cheaper + European + private’ filtresi.", customer:"KOBİ, developer, procurement ve Avrupa SaaS sağlayıcıları.", revenue:"Affiliate · lead-gen · sponsor · verified listing", risk:"G2, Capterra ve AlternativeTo’nun domain otoritesi.", next:"50 ürün için toplam sahip olma maliyeti ve EU data location karşılaştırması hazırla.", source:"G2 / Capterra boşlukları · EU hosting talebi" },
  { id:"ai-replace", rank:14, score:84, name:"Can I Replace It With AI?", short:"Replace Radar", category:"media", label:"AI decision", geography:"Global", model:"Sponsor · Affiliate", mvp:"2–4 hafta", color:"blue", summary:"Bir SaaS, meslek veya operasyonun AI ile tamamen, kısmen ya da hiç değiştirilemeyeceğini görev bazında açıklar.", wedge:"Sansasyonel ‘AI işini elinden alır’ değil; görev matrisi + insan sınırı.", customer:"Founder, SMB, creator ve AI tool sponsorları.", revenue:"Sponsor · affiliate · paid playbook", risk:"Hızlı değişen AI pazarı ve yüzeysel içerik riski.", next:"10 pahalı SaaS için görev matrisi ve gerçek alternatif workflow’u yayınla.", source:"AI adoption / programmatic SEO model" },
  { id:"private-workspace", rank:15, score:82, name:"Private AI Workspace", short:"PrivateDesk", category:"trust", label:"Privacy-first", geography:"EU / DACH", model:"B2B SaaS", mvp:"8–12 hafta", color:"lime", summary:"PDF, mail, görev ve toplantı notlarını local-first işleyen; dokümanı bilgisayardan çıkarmayan AI çalışma alanı.", wedge:"Genel Notion alternatifi değil; Kanzlei, tax advisor ve cybersecurity ekiplerine özel.", customer:"Gizli dokümanla çalışan küçük profesyonel ekipler.", revenue:"€19–79/user/ay · private deployment", risk:"On-device model UX’i, destek yükü ve güçlü incumbents.", next:"Tek bir cyber veya tax ekibinde 100 dokümanlık offline retrieval pilotu.", source:"Anytype · Reborn Apps · Nesis · PilotOS" },
  { id:"restaurant", rank:16, score:80, name:"AI Restaurant OS", short:"GastroOS", category:"b2b", label:"Vertical AI", geography:"DACH / EU", model:"B2B SaaS", mvp:"8–12 hafta", color:"coral", summary:"Stok, tedarik, invoice reconciliation, vardiya, prep ve menu engineering’i tek operasyon katmanında birleştirir.", wedge:"Chatbot değil; restoran sahibinin günlük back-office’ini yöneten karar sistemi.", customer:"2–20 şubeli restoran grupları ve bağımsız işletmeler.", revenue:"€199–999/ay · setup · partner integrations", risk:"POS/ERP entegrasyonları ve restoran operasyonunun dağınıklığı.", next:"Bir mutfakta stok + invoice reconciliation’ı 30 gün manuel destekle ölç.", source:"Marble · GastroKalk · restaurant-tech hareketi" },
];

const categoryNames={all:"Tümü",b2b:"B2B / operasyon",trust:"Güvenlik / uyum",commerce:"Commerce / recovery",media:"SEO / network"};
const categoryGlyphs={b2b:"↗",trust:"◌",commerce:"⌁",media:"✳"};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
let activeId="freight";let activeFilter="all";

function scoreClass(score){return score>=90?"high":score>=85?"mid":"watch"}
function renderCards(){
  const query=$("#search").value.trim().toLocaleLowerCase("tr-TR");
  const sort=$("#sort").value;
  let visible=opportunities.filter(item=>(activeFilter==="all"||item.category===activeFilter)&&(!query||`${item.name} ${item.short} ${item.geography} ${item.label}`.toLocaleLowerCase("tr-TR").includes(query)));
  if(sort==="mvp") visible.sort((a,b)=>parseInt(a.mvp)-parseInt(b.mvp)||b.score-a.score);
  if(sort==="market") visible.sort((a,b)=>(b.geography.includes("Türkiye")?1:0)-(a.geography.includes("Türkiye")?1:0)||b.score-a.score);
  if(sort==="score") visible.sort((a,b)=>b.score-a.score);
  $("#result-count").textContent=visible.length;
  $("#opportunity-grid").innerHTML=visible.length?visible.map(item=>`<button class="op-card ${activeId===item.id?"selected":""}" data-id="${item.id}" style="--card-accent:${item.color}"><div class="op-card-top"><span class="op-glyph ${item.color}">${categoryGlyphs[item.category]||"•"}</span><span class="op-rank">${String(item.rank).padStart(2,"0")}</span><span class="op-score ${scoreClass(item.score)}">${item.score}</span></div><div class="op-card-main"><span class="op-label">${esc(item.label)} · ${esc(item.geography)}</span><h3>${esc(item.name)}</h3><p>${esc(item.summary)}</p></div><div class="op-card-foot"><span>${esc(item.model)}</span><span>${esc(item.mvp)} <b>↗</b></span></div></button>`).join(""): `<div class="empty"><strong>Bu filtrede fırsat yok.</strong><span>Aramayı veya kategori filtresini değiştir.</span></div>`;
  document.querySelectorAll(".op-card").forEach(card=>card.addEventListener("click",()=>{activeId=card.dataset.id;renderCards();renderInsight()}));
}
function renderInsight(){
  const item=opportunities.find(x=>x.id===activeId)||opportunities[0];
  $("#insight-panel").innerHTML=`<div class="insight-kicker"><span class="insight-dot ${item.color}"></span>${esc(item.label)} / seçili fırsat</div><div class="insight-heading"><div><span class="insight-score ${scoreClass(item.score)}">${item.score}</span><span class="out-of">/100</span></div><span class="insight-rank">#${String(item.rank).padStart(2,"0")} conviction rank</span></div><h2>${esc(item.name)}</h2><p class="insight-summary">${esc(item.summary)}</p><div class="insight-grid"><div><span class="detail-label">Başlangıç wedge’i</span><p>${esc(item.wedge)}</p></div><div><span class="detail-label">İlk müşteri</span><p>${esc(item.customer)}</p></div><div><span class="detail-label">Gelir modeli</span><p>${esc(item.revenue)}</p></div><div><span class="detail-label">Öldürücü risk</span><p>${esc(item.risk)}</p></div></div><div class="next-test"><span class="detail-label">İlk 30 gün testi</span><strong>${esc(item.next)}</strong></div><div class="evidence"><span class="detail-label">Signal notes</span><span>${esc(item.source)}</span></div><a class="insight-link" href="#portfolio">Portföy sırasındaki yerini gör <span>↘</span></a>`;
}
document.querySelectorAll(".filter").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));button.classList.add("active");activeFilter=button.dataset.filter;renderCards()}));
$("#search").addEventListener("input",renderCards);$("#sort").addEventListener("change",renderCards);
document.querySelectorAll("[data-jump]").forEach(link=>link.addEventListener("click",event=>{event.preventDefault();activeId=link.dataset.jump;activeFilter="all";document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x.dataset.filter==="all"));renderCards();renderInsight();$("#radar").scrollIntoView({behavior:"smooth"})}));
renderCards();renderInsight();
